### PR TITLE
Reduces the number of different transactions

### LINKED ISSUE #4: Too many metric names being created
I installed this plugin on a client site last week and all was looking good. But over the weekend New Relic opened a ticket saying "This ticket was created due to a very large number of metric names being created for your php application"

It appears that a distinct transation type is being created for each custom post type, tag, category and page. 183 were created before New Relic stopped allowing new metric creation on this application.

### PR DESCRIPTION
**Pull request by nicholasio**
This reduces the number of different transaction by grouping some of them and logging addional info as custom attributes.

This fixes #4.

### CODE REVIEW

**Comment by brandwaffle** [comment]
@nicholasio this looks right to me! Good call with the custom param prefixing.

I'm seeing some weirdness on formatting in the PR. Can you correct that and resubmit and I'll merge?

Thanks!

**Comment by nicholasio** [comment]
@brandwaffle sorry about that, I'll fix formatting. About param prefixing do you want me to add that to all custom parameters? the ones that were already being sent I left intact (post_id, theme, template), it might be a good a idea to prefix all of them but I did checked and there's no conflict with NRQL reserved words.

**Comment by brandwaffle** [comment]
@nicholasio let's leave them as-is for now--I'd rather not change how existing data is being recorded for folks already running this in production, since there are no conflicts.

**Comment by nicholasio** [comment]
@brandwaffle indentation has been fixed.

**Pull request merged**
