### PR TITLE
Mark repo as `stable`

### LINKED ISSUE #63: Update Support Level from Active to Stable
### Is your enhancement related to a problem? Please describe.

Once the following are completed:
- [x] #61
- [x] #53
- [x] #62
- [x] #8

... we can then work to update the support level for this plugin from Active to Stable as we can generally consider the optimal feature set of the plugin complete.  Tasks to complete this change:
- [ ] create a sticky forum post like https://wordpress.org/support/topic/read-this-before-you-post-64/
- [ ] make repo updates like https://github.com/10up/Ad-Refresh-Control/pull/73

### Designs

n/a

### Describe alternatives you've considered

n/a

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Designs

_No response_

### Describe alternatives you've considered

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by jeffpaul**
### Description of the Change
This PR updates the Support Level to `stable` and adds a caution notice to the README noting the same.

### Changelog Entry

> Changed - Support Level downgraded from `Active` to `Stable`.

### Credits

Props @jeffpaul.

### Checklist:

- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests pass.

### CODE REVIEW

**Review by dkotter — DISMISSED** [review]

**Comment by jeffpaul** [comment]
@oscarssanchez I assume that you'd prefer to have this project as `stable` and not `archived`?

**Comment by felipeelia** [comment]
FWIW we will be marking the project as `stable` (as described [here](https://10up.github.io/Open-Source-Best-Practices/github-process/#support-levels))

**Comment by jeffpaul** [comment]
@felipeelia FYI that I changed this from `archived` to `stable` per your request.  Feel free to review/merge when you're ready.

**Review by oscarssanchezz — APPROVED** [review]
LGTM!

**Pull request merged**
